version: "2.3"

services:

  rabbitmq:
    build:
      context: .
      dockerfile: ./docker/rabbitmq/Dockerfile
    networks:
      - network_1
    ports:
      - 5672:5672
    tty: true

  producer:
    build:
      context: .
      dockerfile: ./docker/producer/Dockerfile
    image: producer:0.1.0
    networks:
      - network_1
    depends_on: 
      - rabbitmq
    tty: true
    restart: always


  consumer:
    build:
      context: .
      dockerfile: ./docker/consumer/Dockerfile
    image: consumer:0.1.0
    networks:
      - network_1
    depends_on: 
      - rabbitmq
    tty: true
    restart: always


networks: 
  network_1:
    driver: bridge