version: "2.3"

services:

  rabbitmq:
    build:
      context: .
      dockerfile: ./docker/rabbitmq/Dockerfile
    networks:
      - notification
    ports:
      - 5672:5672
    tty: true

  notification:
    build:
      context: .
      dockerfile: ./docker/notification/Dockerfile
    image: notification:0.1.0
    networks:
      - notification
    depends_on: 
      - rabbitmq
    tty: true
    entrypoint: go run main.go
      
networks: 
  notification:
    driver: bridge