version: "3.9"

services: 
    mqtt-server:
        build: 
            context: ./mqtt_setting
            dockerfile: Dockerfile
        networks: 
            - blog
        ports: 
            - 1883:1883
        entrypoint: mosquitto -c /mosquitto-no-auth.conf
        
networks: 
    blog:
        name: blog
        driver: bridge