version: "3.9"

services: 
    mqtt-server:
        build: 
            context: ./mqtt_setting
            dockerfile: Dockerfile
        networks: 
            - blog
        ports: 
            - 1883:1883
        entrypoint: mosquitto -c /mosquitto-no-auth.conf

    publisher:
        build: 
            context: .
            dockerfile: Dockerfile
        networks: 
            - blog
        volumes: 
            - ${PWD}:/workspace
        environment:
            - NUM=1
            - TIMES=${TIMES}
            - PUBLISHER_NUM=${PUBLISHER_NUM}
        tty: true
        entrypoint: python3 publisher.py
        restart: always


    subscriber:
        build: 
            context: .
            dockerfile: Dockerfile
        networks: 
            - blog
        volumes: 
            - ${PWD}:/workspace
        environment: 
            - NUM=1
            - TIMES=${TIMES}
        entrypoint: python3 subscriber.py
        tty: true
        restart: always

    subscriber:
        build: 
            context: .
            dockerfile: Dockerfile
        networks: 
            - blog
        volumes: 
            - ${PWD}:/workspace
        environment: 
            - NUM=1
            - TIMES=${TIMES}
        entrypoint: python3 subscriber.py
        tty: true
        restart: always

networks: 
    blog:
        name: blog
        driver: bridge