version: "2.3"

services:

  mqtt:
    build:
      context: .
      dockerfile: ./docker/broker/Dockerfile
    networks:
      - network_1
    ports:
      - 1883:1883
    volumes:
      - ${PWD}/docker/broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    tty: true

  producer:
    build:
      context: .
      dockerfile: ./docker/producer/Dockerfile
    image: producer:0.1.0
    networks:
      - network_1
    volumes: 
      - ${PWD}/producer.go:/producer/main.go
    tty: true
    restart: always


  consumer:
    build:
      context: .
      dockerfile: ./docker/consumer/Dockerfile
    image: consumer:0.1.0
    networks:
      - network_1
    volumes: 
      - ${PWD}/consumer.go:/consumer/main.go
    tty: true
    restart: always

networks: 
  network_1:
    driver: bridge